### ISSUE TITLE
when the artical over 149lines, overfollow part will disappear

### ISSUE THREAD

**Issue by Ghost-LZW** [fletchto99/hexo-sliding-spoiler#11]
I use this plugin in my blog soullan.com， this error happen

**Comment by Ghost-LZW** [comment]
temporarily, I use a interesting tag named details to replace this plugin

**Comment by JiaFeiMiao-K-Cat** [comment]
To fix this bug, we can change the CSS setting.
the file is ".\node_modules\hexo-sliding-spoiler\assets\spoiler.css", find **.spoiler.expanded .spoiler-content**
```CSS
.spoiler.expanded .spoiler-content {
    max-height: 3000px;
    overflow: auto;
}
```
change the **overflow** from **hidden** to **auto**, or change the **max-height** to a bigger number.
